### ISSUE TITLE
'module' object has no attribute 'txt' while trying import just

### ISSUE THREAD

**Issue by Bennyelg** [kootenpv/just#4]
In [4]: import just
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-28afee16e27e> in <module>()
----> 1 import just

/usr/local/lib/python2.7/site-packages/just/__init__.py in <module>()
      9 import os
     10
---> 11 import just.txt as txt
     12 import just.json_ as json
     13 import just.newl as newl

AttributeError: 'module' object has no attribute 'txt'

In [5]:

**Comment by kootenpv** [comment]
Hey, thanks for posting. Could you try the latest version? I can just import it in 2.7 myself.

    pip install -U --no-cache just

**Comment by Bennyelg** [comment]
I just installed it.
I'll try now

**Comment by Bennyelg** [comment]
Great it works.
